# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Build and NPM publish
        run: |
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DXOS"
          yarn
          yarn lint
          yarn build
          yarn test
          npm whoami
          yarn lerna publish -y prerelease --dist-tag="beta" --force-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          DX_REGISTRY_USER_KEY: ${{secrets.registry_user_key}}
          DX_REGISTRY_BOND_ID: ${{secrets.registry_bond_id}}
          DX_PROFILE: ci
