name: Build, Test, Lint

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Test
        run: |
          yarn test
      - name: Lint
        run: | 
          yarn lint
